# Generated by Django 4.2.1 on 2023-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
